config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}

  get 'cards/admin', to: 'cards#admin'
  get 'cards/:year/:month/:day', to: 'cards#date'
  get 'cards/today', to: 'cards#today'

  resources :cards

  root to: 'cards#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  validates :year, numericality: { only_integer: true }, allow_nil: true
  validates :month, numericality: { only_integer: true }, allow_nil: true
  validates :day, numericality: { only_integer: true }, allow_nil: true
  validates :source, numericality: { only_integer: true }, allow_nil: true
  validates :era, numericality: { only_integer: true }, allow_nil: true
end

app/models/era.rb
class Era < ActiveYaml::Base
  set_root_path Rails.root.join('config')
end

app/models/role.rb
class Role < ActiveYaml::Base
  set_root_path Rails.root.join('config')
end

app/models/source.rb
class Source < ActiveYaml::Base
  set_root_path Rails.root.join('config')
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  private

    def user
      @user = user_signed_in? ? current_user : nil
      puts @user
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!

  def index
    case Role.find(current_user.role).name
      when 'Admin'
        @cards = Card.all.order(year: :desc, month: :desc, day: :desc)
      when 'Contributor'
        @cards = Card.where(source: current_user.id).order(year: :desc, month: :desc, day: :desc)
      when 'Target'
        @cards = Card.where.not(year: nil).order(year: :desc, month: :desc, day: :desc)
    end
  end

  def create
    @card = Card.new(card_params)

    if !@card.save
      render 'new'
    end

    if params[:card].key?('media')
      uploaded_io = params[:card][:media]
      # File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
      File.open(Rails.root.join('public', @card.id.to_s + '.jpg'), 'wb') do |file|
        file.write(uploaded_io.read)
      end
    end

    redirect_to card_url(@card)
  end

  def new
    @card = Card.new
  end

  def edit
    @card = Card.find(params[:id])
    render(:file => File.join(Rails.root, 'public/404.html'), :status => 404, :layout => false) unless user_can_view?
  end

  def show
    @card = Card.find(params[:id])
    render(:file => File.join(Rails.root, 'public/404.html'), :status => 404, :layout => false) unless user_can_view?
  end

  def date
    @card = Card.where(:year => params[:year])
    @card = @card.where(:month => params[:month])
    @card = @card.where(:day => params[:day])
    if @card.length == 1
      @card = @card.first
    else
      render(:file => File.join(Rails.root, 'public/404.html'), :status => 404, :layout => false)
    end
    render(:file => File.join(Rails.root, 'public/404.html'), :status => 404, :layout => false) unless user_can_view?
  end

  def today
    @card = Card.where(:year => Time.zone.today.year)
    @card = @card.where(:month => Time.zone.today.month)
    @card = @card.where(:day => Time.zone.today.day)
    if @card.length == 1
      @card = @card.first
    else
      render(:file => File.join(Rails.root, 'public/404.html'), :status => 404, :layout => false)
    end
    render(:file => File.join(Rails.root, 'public/404.html'), :status => 404, :layout => false) unless user_can_view?
  end

  def update
    @card = Card.find(params[:id])
    render(:file => File.join(Rails.root, 'public/404.html'), :status => 404, :layout => false) unless user_can_view?

    if params[:card].key?('media')
      uploaded_io = params[:card][:media]
      # File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
      File.open(Rails.root.join('public', @card.id.to_s + '.jpg'), 'wb') do |file|
        file.write(uploaded_io.read)
      end
    end

    if @card.update(card_params)
      redirect_to card_url(@card)
    else
      render 'edit'
    end
  end

  def destroy
    @card = Card.find(params[:id])
    render(:file => File.join(Rails.root, 'public/404.html'), :status => 404, :layout => false) unless user_can_view?
    @card.destroy

    redirect_to cards_url
  end

  def admin
    @cards = Card.all
  end

  private
  def card_params
    params.require(:card).permit(
        :title, :description, :source, :era
    )
  end

  def user_can_view?
    unless @card
      return false
    end
    if current_user.id == @card.source
      true
    elsif current_user.role == 1
      true
    elsif (current_user.role == 2) && (@card.year != nil)
      true
    else
      false
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card.html.erb
<div class="card horizontal small blue-grey darken-1">
  <div class="card-image">
    <% if FileTest.exist?(Rails.root.join('public', "#{card.id}.jpg")) %>
        <%= image_tag "#{root_url}#{card.id}.jpg" %>
    <% end %>
  </div>
  <div class="card-stacked">
    <div class="card-content white-text">
      <span class="card-title"><%= card.title %></span>
      <p><%= card.description %></p>
    </div>
    <div class="card-action">
      <% if card.source %>
        <a href="#" class="chip black-text">
          <%= image_tag "#{root_url}/sources/#{card.source}.jpg" %>
          <%= User.find(card.source).name %>
        </a>
      <% end %>
      <% if card.era %>
          <a href="#" class="chip black-text">
            <%= Era.find(card.era).name %>
          </a>
      <% end %>
    </div>
  </div>
</div>

app/views/cards/_form.html.erb
<div class="container">
  <div class="row">
    <%= form_for @card, html: {:class => 'col s12'} do |f| %>
      <div class="row">
        <% if @card.errors.any? %>
            <div id="error_explanation">
              <h2>
                <%= pluralize(@card.errors.count, 'error') %> prohibited
                this card from being saved:
              </h2>
              <ul>
                <% @card.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="input-field col s12">
          <%= f.text_field :title, class: 'validate' %>
          <%= f.label :title %>
        </div>

        <div class="input-field col s12">
          <%= f.text_area :description, class: 'materialize-textarea' %>
          <%= f.label :description %>
        </div>

        <div class="input-field col s6">
          <% if current_user.role == 1 %>
          <%= collection_select :card, :source, User.where.not(role: 2), :id, :name %>
          <% else %>
          <%= collection_select :card, :source, User.where(id: current_user.id), :id, :name %>
          <% end %>
          <%= f.label :source %>
        </div>
        <div class="input-field col s6">
          <%= collection_select :card, :era, Era.all, :id, :name, prompt: true %>
          <%= f.label :era %>
        </div>

        <div class="file-field input-field col s12">
          <div class="btn">
            <span>Picture</span>
            <!--<input type="file">-->
            <%= f.file_field :media %>
          </div>
          <div class="file-path-wrapper">
            <input class="file-path validate" type="text">
          </div>
        </div>

        <%= f.submit class: 'btn waves-effect waves-light' %>
      </div>
    <% end %>
  </div>
</div>

app/views/cards/_menu.html.erb
<div class="fixed-action-btn">
  <%= link_to ('<i class="large material-icons">menu</i>').html_safe, cards_path, class: 'btn-floating btn-large red' %>
  <ul>
    <% unless (@card.nil?) || (@card.id.nil?) %>
    <li><%= link_to ('<i class="material-icons">delete</i>').html_safe, "/cards/#{@card.id}", class: 'btn-floating red', method: :delete, data: { confirm: 'Are you sure?' } %></li>
    <li><%= link_to ('<i class="material-icons">mode_edit</i>').html_safe, "/cards/#{@card.id}/edit", class: 'btn-floating yellow darken-1' %></li>
    <% end %>
    <!--<li><%= link_to ('<i class="material-icons">library_add</i>').html_safe, new_card_path, class: 'btn-floating green' %></li>-->
    <li><%= link_to ('<i class="material-icons">add</i>').html_safe, new_card_path, class: 'btn-floating blue' %></li>
  </ul>
</div>

app/views/cards/_timeline.html.erb
<section id="cd-timeline">
  <% cards.each do |c| %>
    <% if c.year %>
      <div class="cd-timeline-block">
        <div class="cd-timeline-img">
          <% if FileTest.exist?(Rails.root.join('public', 'sources', "#{c.source}.jpg")) %>
            <%= image_tag "#{root_url}/sources/#{c.source}.jpg", alt: User.where(id: c.source).name %>
          <% else %>
            <i class="material-icons medium">perm_identity</i>
          <% end %>
        </div>

        <div class="cd-timeline-content">
          <h2><%= link_to c.title, card_path(c) %></h2>
          <p class="truncate"><%= c.description %></p>
          <span class="cd-date"><%= c.year %>-<%= c.month %>-<%= c.day %></span>
        </div>
      </div>
    <% end %>
  <% end %>
</section>

app/views/cards/admin.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="<%= cards_path %>"><i class="fa fa-picture-o fa-fw"></i>Cards <span class="badge badge-info"><%= @cards.count %></span></a></li>
        <li><a href="<%= new_card_path %>"><i class="fa fa-plus-circle fa-fw"></i>New Card</a></li>
        <li><a href="<%= Time.zone.now.year %>/<%= Time.zone.now.month %>/<%= Time.zone.now.day %>"><i class="fa fa-calendar fa-fw"></i>Today</a></li>
        <li><a href="<%= root_url %>rails/mailers/card_mailer/daily.html" target="_blank"><i class="fa fa-envelope fa-fw"></i>Preview Email</a></li>
        <li><a href=""><i class="fa fa-cogs fa-fw"></i>Settings</a></li>
      </ul>
    </div>
    <div class="col-md-9 well">
      <table class="table table-striped table-condensed">
        <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Status</th>
          <th colspan="2"></th>
        </tr>
        </thead>
        <tbody>
        <% @cards.each do |card| %>
        <tr>
          <td><%= link_to truncate(card.title, length: 15), card_path(card) %></td>
          <td><%= link_to truncate(card.description, length: 25), card_path(card) %></td>
          <td><% if card.year %><span class="label label-success"><%= card.year %>-<%= card.month %>-<%= card.day %></span><% else %><span class="label label-info">Inactive</span><% end %></td>
          <td><%= link_to 'Edit', edit_card_path(card) %></td>
          <td><%= link_to 'Delete', card_path(card),
                          method: :delete,
                          data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/cards/date.html.erb
<%= render 'card' %>

app/views/cards/edit.html.erb
<%= render 'form' %>

app/views/cards/index.html.erb
<% if [1, 3].include? current_user.role %>
    <% if current_user.role == 3 %><h5 class="center-align">Your Contributions</h5><% end %>
  <ul class="collection with-header">
    <li class="collection-header"><h4>Viewed Cards</h4></li>
    <%= render partial: 'timeline', locals: {cards: @cards} %>
  </ul>
  <ul class="collection with-header">
    <li class="collection-header"><h4>Unseen Cards</h4></li>
    <% @cards.each do |c| %>
      <% if c.year.nil? %>
        <li class="collection-item">
          <div>
            <%= link_to c.title, card_path(c) %>
            <%= link_to '<i class="material-icons secondary-content">delete</i>'.html_safe, card_path(c), method: :delete, data: { confirm: 'Are you sure?' } %>
            <%= link_to '<i class="material-icons secondary-content">mode_edit</i>'.html_safe, edit_card_path(c) %>
            <%= link_to '<i class="material-icons secondary-content">zoom_in</i>'.html_safe, card_path(c) %>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
<% else %>
  <%= render partial: 'timeline', locals: {cards: @cards} %>
<% end %>

app/views/cards/new.html.erb
<%= render 'form' %>

app/views/cards/show.html.erb
<div class="col s12 m7">
  <%= render partial: 'card', locals: { card: @card } %>
</div>

app/views/cards/today.html.erb
<div class="col s12 m7">
    <%= render partial: 'card', locals: { card: @card } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DailyTribute</title>
    <%= csrf_meta_tags %>

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'cards/menu' %>
    <nav>
      <div class="nav-wrapper green lighten-4">
        <a href="<%= cards_path %>" class="brand-logo black-text" style="margin-left: 1em;"><i class="material-icons">home</i></a>
        <ul class="right hide-on-med-and-down">
          <li>
            <%= render partial: 'users/shared/login_items' %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/shared/_links.html.erb
<div class="divider" style="margin-top: 1em; margin-bottom: 1em;"></div>

<div class="collection with-header">
  <h5 class="collection-header">Other Options</h5>

<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: 'collection-item' %>
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: 'collection-item' %>
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: 'collection-item' %>
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class: 'collection-item' %>
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class: 'collection-item' %>
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), class: 'collection-item' %>
  <% end -%>
<% end -%>

</div>

app/views/users/shared/_login_items.html.erb
<% if user_signed_in? %>
  <div class="waves-effect waves-teal btn-flat"><%= current_user.name %></div>
  <%= link_to('Logout', destroy_user_session_path, class: 'waves-effect waves-light btn')  %>
<% else %>
  <%= link_to('Login / Sign-up', new_user_session_path, class: 'waves-effect waves-light btn')  %>
<% end %>